### ISSUE TITLE
How to trigger the Solidity compiler?

### ISSUE THREAD

**Issue by ivica7** [Yakindu/solidity-ide#87]
I configured the path to the solidity compiler via the Solidity preference page.
-> /usr/local/bin/solcjs

When I try to build the project the compiler is not triggered. No output files are generated.

**Comment by flantony** [comment]
The use of solcjs is currently not supported. You should use the win/linux binaries provided here https://github.com/ethereum/solidity/releases and enter the absolute path to solc as preference. For MacOS you currently have to build it from source. If you don't provide a path the IDE will fallback to the solc 0.4.18 which is part of the distro. (works on Windows, should Work on linux as well)

**Comment by ivica7** [comment]
When you say absolute path to solc. in which form do you mean it:
1. /usr/local/bin
1. /usr/local/bin/solc

**Comment by ivica7** [comment]
Event if solcjs is not supported, I was expecting to see the compiler being triggered at least if I provide the path to it. But this doesn't seem to be the case.

**Comment by flantony** [comment]
You are absolutely right about the user feedback… there is none. 
But the call to the compiler, or whatever there might be on the end of the provided path is executed. In my case, if I provide a path to solcjs, an exception occurred  stating ‘solcjs’ is not a proper Win32 Application. But since there is no user-level-error reporting in place this is not visible except while debugging. I created #92 to tackle this issue. 

Regarding the compiler output is should now located in the folder specified in the preference relative to the project that contains the file that was compiled. 
Make sure you have refreshed your workspace, or make sure Window > Preference > General > Workspace > “Refresh using native hooks or polling” is enabled

**Comment by ivica7** [comment]
‘solcjs’ is not a proper Win32 Application <- how this check/error comes? As far as I know, solcjs is compatible to solc. If one could remove this check, it could also work with solcjs (wild guess)?

**Comment by axic** [comment]
@flantony it should be possible to use `solcjs` as a drop-in replacement for `solc` when using the `--standard-json` mode, however:
- there is a bug in `solcjs` (piping doesn't work properly with node.js) which breaks `--standard-json` on it
- it is way slower to load the Emscripten-ized compiler version (can be 2-3 seconds) compared to the native binary

I'd advise against using it at the moment.

**Comment by flantony** [comment]
@axic thank you for the hint, I'll take a look into it and check if I can make it run now that we use the "--standard-json" option for the compiler. This is probably good news for some mac users, even if its not optimal, it's more convenient than building binaries form source. If it works i'll add a validation to the preference, to warns the user about the discouraged use of solcjs.

**Comment by flantony** [comment]
Ok, calling solcjs --standard-json works, but I am getting different results as if i call solc for the same input. 
The warnings/errors seam to be the same, but I'm not seeing any binaries, AST, assembly, ABI in the result. There is either a bug in solcjs, or I am providing malformed input[, which I think is very likely]. 
In the latter case I wonder why solc accepts the same input without complaining. 
Is it possible that solc defaults to putting out ast,asm,bin&abi if the input is malformed?
